### ISSUE TITLE
Frama-C problem with ocaml 4.06.0

### ISSUE THREAD

**Issue by jensgerlach** [Frama-C/Frama-C-snapshot#13]
I am not sure this problem is particularly related to the Argon release but I would like to point it out anyway.

On xubuntu-18.04, with opam 2.0.1 and trying to execute the following steps
- `opam init --comp=4.06.0`
- `opam install depext`
- `opam depext frama-c`

I receive the following error message.

```
Fatal error: cannot load shared library dllunix
Reason: /usr/lib/ocaml/stublibs/dllunix.so: undefined symbol: caml_strdup```

**Comment by maroneze** [comment]
Hello,

Did you manage to test it again after the `opam update`?

**Comment by jensgerlach** [comment]
After re-installing opam (2.0.1) and intirialising it with ocaml 4.06.1 the error message is gone!

Regards

Jens

**Comment by maroneze** [comment]
Thanks, I'll close the issue then.
