### ISSUE TITLE
frama-clang install error: cannot shared library dllunix

### ISSUE THREAD

**Issue by gjxo12** [Frama-C/Frama-C-snapshot#36]
Hi, i'm tyring to install frama-clang plugin now, but some error happen.

I use Ubuntu-18.04 and my opam, ocaml version is 2.0.4 and 4.07.0

I tried every bug Issue solution but 'make' command failed

my Log is here.

```
pl@pl-VirtualBox:~/frama-clang-0.0.7$ ./configure 
checking for frama-c-gui... yes
checking for Makefile.config.in... yes
frama_clang... yes
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for camlp4o... yes
checking for clang... clang
checking for clang++... clang++
checking for llvm-config... llvm-config
checking for /usr/lib/llvm-6.0/include/clang... yes
checking LLVM version... 6.0.0: Good
configure: frama_clang: yes
configure: creating ./config.status
config.status: creating ./Makefile.config

pl@pl-VirtualBox:~/frama-clang-0.0.7$ make
Ocamlc       gen_ast
Fatal error: cannot load shared library dllunix
Reason: /home/pl/.opam/4.07.0/lib/ocaml/stublibs/dllunix.so: undefined symbol: caml_ba_element_size
File "gen_ast.ml", line 1:
Error: Error while running external preprocessor
Command line: camlp4o 'gen_ast.ml' > /tmp/ocamlpp66b132

make: *** 'intermediate_format_parser.ml'에서 필요한 'gen_ast' 타겟을 만들 규칙이 없습니다.  멈춤.

pl@pl-VirtualBox:~/frama-clang-0.0.7$ ocaml --version
The OCaml toplevel, version 4.07.0
pl@pl-VirtualBox:~/frama-clang-0.0.7$ opam --version
2.0.4
pl@pl-VirtualBox:~/frama-clang-0.0.7$ opam switch
#  switch  compiler                    description
   4.06.1  ocaml-base-compiler.4.06.1  4.06.1
→  4.07.0  ocaml-base-compiler.4.07.0  4.07.0
```

I guess the version is incompatible. but i can't fix this error. Could you help me?

Please let me know if you need any other information.  

thanks.

**Comment by maroneze** [comment]
I see a few issues related to OCaml 4.06.1 (https://github.com/ocaml/opam/issues/3573), but I assumed you tried them already? Something like `opam switch remove 4.06.1; opam reinstall ocaml-base-compiler.4.07.0`, to get rid of "broken" switches and install a new one, seems a possible solution, according to the linked issue.

Otherwise, would you by chance have any Ubuntu OCaml packages installed? If so, I'd recommend uninstalling them, to avoid mixing opam and non-opam OCaml binaries. Something such as `apt remove "*ocaml*"` should do the trick.

Note that this is an issue with OCaml and camlp4, and not Frama-Clang itself (which uses camlp4), and the issue is not trivially reproducible. We can try to provide some help, but ultimately it resides within OCaml/camlp4.

**Comment by gjxo12** [comment]
Thank you for your rapid response.
today morning, I behave your counsel. First, I remove opam 4.06.1 and reinstall ocam-base-compiler.4.07.0,  Second, I type in 'apt remove "*ocaml*"'

after this activity, I try to install 'frama-clang plugin' and this is what i entered. as a results, a Error messages is changed. 

pl@pl-VirtualBox:~/frama-clang-0.0.7$ opam switch
#  switch  compiler                    description
→  4.07.0  ocaml-base-compiler.4.07.0  4.07.0


pl@pl-VirtualBox:~/frama-clang-0.0.7$ opam init

<><> Required setup - please read <><><><><><><><><><><><><><><><><><><><><><><>

  In normal operation, opam only alters files within ~/.opam.

  However, to best integrate with your system, some environment variables
  should be set. If you allow it to, this initialisation step will update
  your bash configuration by adding the following line to ~/.profile:

    test -r /home/pl/.opam/opam-init/init.sh && . /home/pl/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true

  Otherwise, every time you want to access your opam installation, you will
  need to run:

    eval $(opam env)

  You can always re-run this setup with 'opam init' later.

Do you want opam to modify ~/.profile? [N/y/f]
(default is 'no', use 'f' to choose a different file) no
A hook can be added to opam's init scripts to ensure that the shell remains in sync with the opam environment when they are loaded. Set that up? [y/N] y

pl@pl-VirtualBox:~/frama-clang-0.0.7$ eval $(opam env)

pl@pl-VirtualBox:~/frama-clang-0.0.7$ ./configure 
checking for frama-c-gui... yes
checking for Makefile.config.in... yes
frama_clang... yes
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for camlp4o... no
configure: WARNING: camlp4o not found.
configure: WARNING: frama_clang disabled because camlp4o missing.
checking for clang... clang
checking for clang++... clang++
checking for llvm-config... llvm-config
checking for /usr/lib/llvm-6.0/include/clang... yes
configure: frama_clang: no
configure: creating ./config.status
config.status: creating ./Makefile.config

pl@pl-VirtualBox:~/frama-clang-0.0.7$ make
Ocamlc       gen_ast
sh: 1: zarith.cma: not found
File "gen_ast.ml", line 1:
Error: Error while running external preprocessor
Command line: zarith.cma 'gen_ast.ml' > /tmp/ocamlppe99e45

make: *** 'intermediate_format_parser.ml'에서 필요한 'gen_ast' 타겟을 만들 규칙이 없습니다.  멈춤.


in my opinion, a command './configure' ,line 12 , 'checking for camlp4o... no' suspicion.
changed Error messange is 'Error while running external preprocessor' so i search this mesaage in web site but can't fix Error.

**Comment by maroneze** [comment]
What's happening is that you have an incompatible version of Frama-C (20.0 or our Gitlab development version); Frama-Clang has not yet been released since Frama-C 20.0 came out.
The 0.0.7 version in particular states in its requirements:

> ### Requirements
>
> - Frama-C 19.0 Potassium

So, you'll need to downgrade your version of Frama-C (usually, `opam install frama-c.19.0` should suffice) and then try to compile Frama-Clang again.

**Comment by gjxo12** [comment]
I remove frama-c.20.0 version, and install frama-c.19.0 using command 'opam install frama-c.19.0.

i pinned 19.0 version using command 'opam pin add frama-c 19.0' 
and i type command. here is my Log.

<pre>
<code>
pl@pl-VirtualBox:~/frama-clang-0.0.7$ opam pin add frama-c 19.0
frama-c is now pinned to version 19.0


pl@pl-VirtualBox:~/frama-clang-0.0.7$ opam init --disable-sandboxing

<><> Required setup - please read <><><><><><><><><><><><><><><><><><><><><><><>

  In normal operation, opam only alters files within ~/.opam.

  However, to best integrate with your system, some environment variables
  should be set. If you allow it to, this initialisation step will update
  your bash configuration by adding the following line to ~/.profile:

    test -r /home/pl/.opam/opam-init/init.sh && . /home/pl/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true

  Otherwise, every time you want to access your opam installation, you will
  need to run:

    eval $(opam env)

  You can always re-run this setup with 'opam init' later.

Do you want opam to modify ~/.profile? [N/y/f]
(default is 'no', use 'f' to choose a different file) no
A hook can be added to opam's init scripts to ensure that the shell remains in
sync with the opam environment when they are loaded. Set that up? [y/N] y
pl@pl-VirtualBox:~/frama-clang-0.0.7$ eval $(opam env)
pl@pl-VirtualBox:~/frama-clang-0.0.7$ opam install depext
[NOTE] Package depext is already installed (current version is transition).
pl@pl-VirtualBox:~/frama-clang-0.0.7$ opam depext frama-c
# Detecting depexts using vars: arch=x86_64, os=linux, os-distribution=ubuntu, os-family=debian
# The following system packages are needed:
autoconf
debianutils
graphviz
libexpat1-dev
libgmp-dev
libgnomecanvas2-dev
libgtk2.0-dev
libgtksourceview2.0-dev
m4
perl
pkg-config
zlib1g-dev
# All required OS packages found.
pl@pl-VirtualBox:~/frama-clang-0.0.7$ ./configure 
checking for frama-c-gui... yes
checking for Makefile.config.in... yes
frama_clang... yes
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for camlp4o... yes
checking for clang... clang
checking for clang++... clang++
checking for llvm-config... llvm-config
checking for /usr/lib/llvm-6.0/include/clang... yes
checking LLVM version... 6.0.0: Good
configure: frama_clang: yes
configure: creating ./config.status
config.status: creating ./Makefile.config
pl@pl-VirtualBox:~/frama-clang-0.0.7$ make
Ocamlc       convert.cmo
File "convert.ml", line 1:
Error: The files /home/pl/.opam/4.07.0/lib/frama-c/cabs.cmi and cxx_utils.cmi
       make inconsistent assumptions over interface Filepath
/home/pl/.opam/4.07.0/share/frama-c/Makefile.generic:77: recipe for target 'convert.cmo' failed
make: *** [convert.cmo] Error 2
pl@pl-VirtualBox:~/frama-clang-0.0.7$ frama-c --version
19.0 (Potassium)pl@pl-VirtualBox:~/frama-clang-0.0.7$ 
</code>
<pre>

the new error is occured. what is problem

**Comment by vprevosto** [comment]
It's difficult to say for sure, but it looks like there are leftovers from your previous attempts in the frama-clang directory. Either do a `make clean` before `./configure` or remove the directory altogether and extract a brand new one from the archive `frama-clang-0.0.7.tar.gz`.

By the way, you do not need to do `opam init` each time. This is supposed to be done once when you install `opam` itself. Similarly, `opam install depext` and `opam depext frama-c` are needed only once per `opam switch`.
