### ISSUE TITLE
program slicing

### ISSUE THREAD

**Issue by lyqssb** [Frama-C/Frama-C-snapshot#39]
I am trying to use frama-c to get program slice. I've already read the doc [http://frama-c.com/slicing.html](url). and  I know  there are many options to get program slice. I chose -slice-return to get my slicing. But I met error
my command :frama-c -slice-return main CWE114_Process_Control__w32_char_listen_socket_42.c
the error I met:
[kernel] Parsing FRAMAC_SHARE/libc/__fc_builtin_for_normalization.i (no preprocessing)
[kernel] Parsing CWE114_Process_Control__w32_char_listen_socket_42.c (with preprocessing)
CWE114_Process_Control__w32_char_listen_socket_42.c:136:[kernel] user error: syntax error
[kernel] user error: stopping on file "CWE114_Process_Control__w32_char_listen_socket_42.c" that
                     has errors. Add '-kernel-msg-key pp' for preprocessing command.
[kernel] Frama-C aborted: invalid user input.

I don't know how to fix it.would anyone give me some advice?

**Comment by vprevosto** [comment]
Which version of Frama-C (`frama-c -version`) are you using? `__fc_builtin_for_normalization.i` was removed around 3 years ago. Moreover, if the problem persist with the current version (Frama-C 21.1 Scandium, as available at https://frama-c.com/download.html), it would help to have the source that is causing the issue, or at least a URL.

**Comment by lyqssb** [comment]
Hi! Thank you for your response. I download the latest frama-c 21.1 (Scandium). But I got another type error:
my command: frama-c -slicing-return <CWE114_Process_Control__w32_char_file_41.c>
the error: bash: syntax error near unexpected token `newline'
I am wondering if these options  such as -slicing-return should obey some rules which I didn't know. I really need some help. Thank you  @vprevosto 
By the way,this is my file content:
`/* TEMPLATE GENERATED TESTCASE FILE

Filename: CWE114_Process_Control__w32_char_file_41.c

Label Definition File: CWE114_Process_Control__w32.label.xml

Template File: sources-sink-41.tmpl.c

*/

/*

 * @description

 * CWE: 114 Process Control

 * BadSource: file Read input from a file

 * GoodSource: Hard code the full pathname to the library

 * Sink:

 *    BadSink : Load a dynamic link library

 * Flow Variant: 41 Data flow: data passed as an argument from one function to another in the same source file

 *

 * */



#include "std_testcase.h"



#include <wchar.h>



#ifdef _WIN32

#define FILENAME "C:\\temp\\file.txt"

#else

#define FILENAME "/tmp/file.txt"

#endif



#include <windows.h>



#ifndef OMITBAD



void CWE114_Process_Control__w32_char_file_41_badSink(char * data)

{

    {

        HMODULE hModule;

        /* POTENTIAL FLAW: If the path to the library is not specified, an attacker may be able to

         * replace his own file with the intended library */

        hModule = LoadLibraryA(data);

        if (hModule != NULL)

        {

            FreeLibrary(hModule);

            printLine("Library loaded and freed successfully");

        }

        else

        {

            printLine("Unable to load library");

        }

    }

}



void CWE114_Process_Control__w32_char_file_41_bad()

{

    char * data;

    char dataBuffer[100] = "";

    data = dataBuffer;

    {

        /* Read input from a file */

        size_t dataLen = strlen(data);

        FILE * pFile;

        /* if there is room in data, attempt to read the input from a file */

        if (100-dataLen > 1)

        {

            pFile = fopen(FILENAME, "r");

            if (pFile != NULL)

            {

                /* POTENTIAL FLAW: Read data from a file */

                if (fgets(data+dataLen, (int)(100-dataLen), pFile) == NULL)

                {

                    printLine("fgets() failed");

                    /* Restore NUL terminator if fgets fails */

                    data[dataLen] = '\0';

                }

                fclose(pFile);

            }

        }

    }

    CWE114_Process_Control__w32_char_file_41_badSink(data);

}



#endif /* OMITBAD */



#ifndef OMITGOOD



void CWE114_Process_Control__w32_char_file_41_goodG2BSink(char * data)

{

    {

        HMODULE hModule;

        /* POTENTIAL FLAW: If the path to the library is not specified, an attacker may be able to

         * replace his own file with the intended library */

        hModule = LoadLibraryA(data);

        if (hModule != NULL)

        {

            FreeLibrary(hModule);

            printLine("Library loaded and freed successfully");

        }

        else

        {

            printLine("Unable to load library");

        }

    }

}



/* goodG2B uses the GoodSource with the BadSink */

static void goodG2B()

{

    char * data;

    char dataBuffer[100] = "";

    data = dataBuffer;

    /* FIX: Specify the full pathname for the library */

    strcpy(data, "C:\\Windows\\System32\\winsrv.dll");

    CWE114_Process_Control__w32_char_file_41_goodG2BSink(data);

}



void CWE114_Process_Control__w32_char_file_41_good()

{

    goodG2B();

}



#endif /* OMITGOOD */



/* Below is the main(). It is only used when building this testcase on

 * its own for testing or for building a binary to use in testing binary

 * analysis tools. It is not used when compiling all the testcases as one

 * application, which is how source code analysis tools are tested.

 */



#ifdef INCLUDEMAIN



int main(int argc, char * argv[])

{

    /* seed randomness */

    srand( (unsigned)time(NULL) );

#ifndef OMITGOOD

    printLine("Calling good()...");

    CWE114_Process_Control__w32_char_file_41_good();

    printLine("Finished good()");

#endif /* OMITGOOD */

#ifndef OMITBAD

    printLine("Calling bad()...");

    CWE114_Process_Control__w32_char_file_41_bad();

    printLine("Finished bad()");

#endif /* OMITBAD */

    return 0;

}



#endif`

**Comment by vprevosto** [comment]
The new error you're mentioning has nothing to do with Frama-C. `<` and `>` are redirection operators in bash (and in any POSIX shell in fact), and they must be followed by a filename or a number (see https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_07 for more information). You can't end your command line with a `>`. Moreover, Frama-C does not read anything from its standard input, so that it is useless to redirect it. The proper command would be `frama-c [options] CWE114_Process_Control__w32_char_file_41.c`.

Moreover there's no `-slicing-return` option, and `-slice-return` takes as argument the list of functions whose returned values will constitute the slicing criterion. Hence, you probably meant `frama-c -slice-return CWE114_Process_Control__w32_char_file_41.c`

Finally, your example is not complete: the header `std_testcase.h` is missing.

**Comment by lyqssb** [comment]
I tried to use frama-c as you said, I changed my command:
`frama-c -slice-return CWE121_Stack_Based_Buffer_Overflow__CWE135_52a.c`
And there is another error:
[slicing] User Error: incorrect argument for option -slice-return
  (no function 'CWE121_Stack_Based_Buffer_Overflow__CWE135_52a.c').
[kernel] Plug-in slicing aborted: invalid user input.
Yes, the `CWE121_Stack_Based_Buffer_Overflow__CWE135_52a.c` is a file. I still don't know how to set a function.
My `std_testcase.h` is another file in the same directory with `CWE121_Stack_Based_Buffer_Overflow__CWE135_52a.c`.  Do I have to get the `std_testcase.h` in the .c file?
Thank you for your help! @vprevosto

**Comment by vprevosto** [comment]
As I have said in my previous answer, `-slice-return` takes an additional argument, namely the list of function whose return value you're interested in (e.g. `main`). Thus, the command line you provided was asking to consider the return value of function `CWE121_Stack_Based_Buffer_Overflow__CWE135_52a.c` and didn't include any source file.

You don't have to get `std_testcase.h` in the `.c` file on your local installation, but provide its content here. As long as you don't provide the complete code base of your issue (preferably minimized, following [stackoverflow guidelines](https://stackoverflow.com/help/mcve)), it's not possible to reproduce the issue, making it more difficult to understand what is going on.

**Comment by lyqssb** [comment]
enmmmm, now I know my real question is how to import a .c file. Where I should provide the file to the frama-c? Is there an accurate directory? I didn't find this part in the user manual. Thank you for your quick and patient answer! @vprevosto

**Comment by lyqssb** [comment]
I tried to use this command:`frama-c CWE121_Stack_Based_Buffer_Overflow__CWE131_loop_04.c -slice-calls goodG2B2` and I got another error:
`[kernel]Parsing CWE121_Stack_Based_Buffer_Overflow__CWE131_loop_04.c (with preprocessing)
[kernel:typing:implicit-function-declaration] CWE121_Stack_Based_Buffer_Overflow__CWE131_loop_04.c:35: Warning: 
  Calling undeclared function alloca. Old style K&R code?
[slicing] slicing requests in progress...
[kernel] User Error: cannot find entry point `main'.
  Please use option `-main' for specifying a valid entry point.
[kernel] Frama-C aborted: invalid user input.`
Would you mind telling me how to fix this? Thank you! @vprevosto
