### ISSUE TITLE
program slicing

### ISSUE THREAD

**Issue by lyqssb** [Frama-C/Frama-C-snapshot#40]
Hi! I  am trying to use frama-c to get slicing of my code file.
My code file:
```
int main(int argc, char *argv[])
{
  size_t len;
  char src[4106];
  char buf[10];
  memset(src, 'A', 4106);
  src[4106 - 1] = '\0';
  len = 4106;
  strncpy(buf, src, len);
  return 0;
}
```

I want to use frama-c to get slicing like this:

```
char buf[10];
src[4106 - 1] = '\0';
len = 4106;
strncpy(buf, src, len);
```

I just want to keep the lines which are related to the callee:`strncpy(buf, src, len);`. 
And are there some commands to automated get these lines even if there are more than one callees?

**Comment by maroneze** [comment]
Frama-C's slicing always produces an executable program. It does not remove *lines* of code, it removes *statements* and simplifies *expressions*, but it does not produce code fragments as in your example (which is missing declarations for variables `src`, and `len`, plus it contains code outside of any function).

To choose the slicing criteria (e.g. the call to `strncpy`), you can use ACSL annotations (e.g. `/*@ slice pragma stmt; */` before the call), or command-line options such as `-slice-calls strcnpy`, as mentioned in the [Slicing plug-in home page](http://frama-c.com/slicing.html).

**Comment by maroneze** [comment]
We are archiving this snapshot repository and moving the issues to our [Gitlab instance](https://git.frama-c.com/pub/frama-c/-/issues).

In case my reply does not completely answer you, please consider posting an issue over there (you can use your Github login).
