### ISSUE TITLE
Warnings while opening GUI : (Few items misplaced)

### ISSUE THREAD

**Issue by systemadminister** [Frama-C/Frama-C-snapshot#41]
I use :
Linux kali 5.7.0-kali1-amd64 #1 SMP Debian 5.7.6-1kali2 (2020-07-01) x86_64 GNU/Linux
Theme is kinda dark.
So, when I launch Frama-c GUI,
It shows the following warnings:
`
** (frama-c-gui:20489): WARNING **: 13:48:57.056: Invalid borders specified for theme pixmap:
        /usr/share/themes/Kali-Dark/gtk-2.0/assets/trough-scrollbar-horiz.png,
borders don't fit within the image

** (frama-c-gui:20489): WARNING **: 13:48:57.056: invalid source position for vertical gradient

** (frama-c-gui:20489): WARNING **: 13:48:57.056: invalid source position for vertical gradient

** (frama-c-gui:20489): WARNING **: 13:48:57.092: invalid source position for vertical gradient

** (frama-c-gui:20489): WARNING **: 13:48:57.092: invalid source position for vertical gradient

** (frama-c-gui:20489): WARNING **: 13:48:57.101: invalid source position for vertical gradient

** (frama-c-gui:20489): WARNING **: 13:48:57.101: invalid source position for vertical gradient`

Also I noticed problem with the span of menu drop-downs

![framac-_gui_issue](https://user-images.githubusercontent.com/67857588/91632590-6fcf2480-e9ff-11ea-9bf9-d17d61169344.png)
and
![framac-_gui_issue2](https://user-images.githubusercontent.com/67857588/91632594-7d84aa00-e9ff-11ea-9885-1f06c4f94a0c.png)

 that in Analyses menu, the parameters are listed in black font with black background which makes difficult to read.
Also I fear that there may be few more issues.
Kindly look into it.

**Comment by systemadminister** [comment]
Also Need to know will that cause any serious issues in any location...

**Comment by maroneze** [comment]
Thank you for reporting this issue.

As mentioned in our [Public Gitlab instance](https://git.frama-c.com/pub/frama-c/-/issues), which is the official channel for bug reports in Frama-C nowadays, there are indeed some usability issues as you noticed with the GTK-based GUI. However, it is being phased out to be replaced with a new, Electron-based GUI, so efforts are being directed towards the latter. If there are quick patches to adopt theses fixes, we may incorporate them, otherwise I'm afraid it'll have to wait for a moment until the new GUI is production-ready.

**Comment by systemadminister** [comment]
> Thank you for reporting this issue.
> 
> As mentioned in our [Public Gitlab instance](https://git.frama-c.com/pub/frama-c/-/issues), which is the official channel for bug reports in Frama-C nowadays, there are indeed some usability issues as you noticed with the GTK-based GUI. However, it is being phased out to be replaced with a new, Electron-based GUI, so efforts are being directed towards the latter. If there are quick patches to adopt theses fixes, we may incorporate them, otherwise I'm afraid it'll have to wait for a moment until the new GUI is production-ready.

Yeah I got it. Anyways Waiting for Electron-based GUI !
Thanks for your response.
