### ISSUE TITLE
why3 not detecting

### ISSUE THREAD

**Issue by mohithsairamreddy** [Frama-C/Frama-C-snapshot#46]
[Error:kernel] User Error: [findlib] package 'why3' not found (required by `frama-c-wp')
Versions:
Frama-c:20.0
why3:1.2.1
alt-ergo:2.0.0
opam-2.0.5

**Comment by maroneze** [comment]
I'm sorry, I'm afraid your report does not contain enough information for us to reproduce it, and also:
- it has been posted to our obsolete Github repository; as indicated in the README, we have moved to https://git.frama-c.com/pub/frama-c;
- it concerns an old version of Frama-C (3 releases ago; we recommend trying the latest release whenever possible);
- the error message comes from external tools used to configure Frama-C, and without extra context information (which commands were used; what's the current opam switch state; OCaml version; etc), it's nearly impossible to reproduce it.

Please consider upgrading Frama-C (or explaining why you need this specific version) and, if you still have an issue, reporting it at https://git.frama-c.com/pub/frama-c/-/issues. This snapshot repository will likely be archived, so all issues will be closed and become read-only.
